import { EvetHayir } from '../enums';
import { QCInfoBase } from '../_base/qc-kayit-onay.base';
import { BobinKalinlikDegerleri } from './bobin-kalinlik-degerleri';
import { OncekiHatKusur } from './onceki-hat-kusur';
import { TCRBilgileri } from './tcr-bilgileri';
import { HSM1UretimDegerleri, HSM2UretimDegerleri } from './uretim-degerleri';

export interface QCKayitBilgileri extends QCInfoBase {
  numuneAlAlaniDisabled: boolean;
  yuzeyKusuruVarMiAlaniDisabled: boolean;
  uretimZamani: Date;
  hatNo: string;
  mpcNo: string;
  denemeMi: string;
  fasonMu: string;
  musteriNo: string;
  musteriAdi: string;
  musteriSpecNo: string;
  protokolLotNo: string;
  sonrakiHat: string;
  cBoxKul: string;
  bobinUzunlugu: number;
  bobinAgirligi: number;
  sariciNo: string;
  uretimSuresi: number;
  standartNumuneNoYeriAlinmaIsareti: string;
  alternatifKalinlik1: number;
  alternatifKalinlik2: number;
  alternatifKalinlik3: number;
  dispozeKodu: string;
  divideCut: string;
  divideCutBolumeDurumu: string;
  oncekiHatYuzeyKusuruSiraNo: string;
  oncekiHatYuzeyKusuruKodu: string;
  oncekiHatYuzeyKusuruAciklama: string;
  oncekiHatYuzeyKusuruDerecesi: string;
  oncekiHatYuzeyKusuruYuzdesi: string;
  oncekiHatYuzeyKusuruYeri: string;
  oncekiHatMesaji: string;
  dokumNo: string;
  slabNo: string;
  bobinNo: string;
  dokumCelikKalitesi: string;
  erdemirCelikKalitesi: string;
  uluslararasiCelikKalitesi: string;
  celikKaliteStandardi: string;
  yerliIhracKodu: string;
  urun: string;
  bobinKalinlikDegerleri: BobinKalinlikDegerleri;
  oncekiHatKusurBilgileriListesi: OncekiHatKusur[];
  tcrBilgileriListesi: TCRBilgileri[];
  hsm1UretimDegerleri: HSM1UretimDegerleri[];
  hsm2UretimDegerleri: HSM2UretimDegerleri[];
  bobinAcmaKontrolu: EvetHayir;
  aciklama: string;
}
